// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// fpa_optim
List fpa_optim(double N, double p, double beta, double eta, int maxiter, bool randEta, double gloMin, double objfit, double D, double Lower, double Upper, Function FUN);
RcppExport SEXP MetaheuristicFPA_fpa_optim(SEXP NSEXP, SEXP pSEXP, SEXP betaSEXP, SEXP etaSEXP, SEXP maxiterSEXP, SEXP randEtaSEXP, SEXP gloMinSEXP, SEXP objfitSEXP, SEXP DSEXP, SEXP LowerSEXP, SEXP UpperSEXP, SEXP FUNSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< double >::type N(NSEXP);
    Rcpp::traits::input_parameter< double >::type p(pSEXP);
    Rcpp::traits::input_parameter< double >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< int >::type maxiter(maxiterSEXP);
    Rcpp::traits::input_parameter< bool >::type randEta(randEtaSEXP);
    Rcpp::traits::input_parameter< double >::type gloMin(gloMinSEXP);
    Rcpp::traits::input_parameter< double >::type objfit(objfitSEXP);
    Rcpp::traits::input_parameter< double >::type D(DSEXP);
    Rcpp::traits::input_parameter< double >::type Lower(LowerSEXP);
    Rcpp::traits::input_parameter< double >::type Upper(UpperSEXP);
    Rcpp::traits::input_parameter< Function >::type FUN(FUNSEXP);
    __result = Rcpp::wrap(fpa_optim(N, p, beta, eta, maxiter, randEta, gloMin, objfit, D, Lower, Upper, FUN));
    return __result;
END_RCPP
}
